version: '3.8'

services:
  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:latest
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: kafka
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  flink-jobmanager:
    build:
      context: ./flink/
      dockerfile: jobmanager.dockerfile
    container_name: jobmanager
    hostname: jobmanager
    ports:
      - "8081:8081"
      - "6123:6123"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - project2-network

  flink-taskmanager:
    build:
      context: ./flink/
      dockerfile: taskmanager.dockerfile
    container_name: taskmanager
    hostname: taskmanager
    depends_on:
      - flink-jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=10
    networks:
      - project2-network

  producer:
    build:
      context: ./producer/
    container_name: producer
    depends_on:
      - kafka
    volumes:
      - ./producer/src:/home/producer/src
    networks:
      - project2-network

networks:
  project2-network:
    driver: bridge
