version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - project-network

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - project-network

  nifi:
    build: ./nifi
    container_name: nifi
    ports:
      - "8443:8443"
      - "8082:8082"
    tty: true
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
        - SINGLE_USER_CREDENTIALS_PASSWORD=${SINGLE_USER_CREDENTIALS_PASSWORD}
        - NIFI_SENSITIVE_PROPS_KEY=${NIFI_SENSITIVE_PROPS_KEY}
        - NIFI_HOME=/opt/nifi/nifi-current
    hostname: nifi
    networks:
      - project-network

  producer:
    build: ./producer
    depends_on:
      - nifi
    networks:
      - project-network

  flink-jobmanager:
    build:
      context: ./flink/
      dockerfile: jobmanager.dockerfile
    container_name: flink-jobmanager
    hostname: jobmanager
    ports:
      - "8081:8081"
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    volumes:
      - ./flink/src:/job
    depends_on:
      - kafka
    networks:
      - project-network

  flink-taskmanager:
    build:
      context: ./flink/
      dockerfile: taskmanager.dockerfile
    container_name: flink-taskmanager
    hostname: taskmanager
    depends_on:
      - flink-jobmanager
    volumes:
      - ./results:/results
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 10
    networks:
      - project-network

networks:
  project-network:
    driver: bridge
