jobmanager.memory.process.size: 1024m
taskmanager.memory.process.size: 1024m
taskmanager.numberOfTaskSlots: 2

metrics.reporters.prom.port: 9249
metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
